version: '3'
services:
  backend:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DB: two_tier
    depends_on:
      - mysql
    
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test@123
      MYSQL_DATABASE: two_tier
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./messages.sql:/docker-entrypoint-initdb.d/messages.sql 
      - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume:


